export const UPDATE_VIDEO_CLIENT = 'UPDATE_VIDEO_CLIENT';
export const UPDATE_ACTIVE_ROOM = 'UPDATE_ACTIVE_ROOM';
export const UPDATE_PREVIEW_MEDIA = 'UPDATE_PREVIEW_MEDIA';
export const UPDATE_IDENTITY = 'UPDATE_IDENTITY';
export const UPDATE_ROOM_NAME = 'UPDATE_ROOM_NAME';
export const UPDATE_ROOM_NAME_INPUT = 'UPDATE_ROOM_NAME_INPUT';
